-- DQ Framework: seed data for reference/config tables (schemachange versioned)
-- Co-authored with CoCo
-- Idempotent reseed - safe to re-run.
-- Generated on 2026-06-21T10:32:32
USE DATABASE DQ_FRAMEWORK;
USE SCHEMA METADATA;

-- DQ_JOB_EXEC_CONFIG (1 rows)
DELETE FROM DQ_FRAMEWORK.METADATA.DQ_JOB_EXEC_CONFIG;
INSERT INTO DQ_FRAMEWORK.METADATA.DQ_JOB_EXEC_CONFIG (DQ_DB_NAME, DQ_SCHEMA_NAME, SAMPLE_ROWS_CNT, SUCCESS_CODE, FAILED_CODE, EXECUTION_ERROR, CREATED_AT, UPDATED_AT) VALUES
    ('DQ_FRAMEWORK', 'METADATA', 'ALL', '200', '300', '400', '2026-06-15 04:17:18.703000', '2026-06-15 04:46:43.105000');

-- DQ_EXPECTATION_MASTER (26 rows)
DELETE FROM DQ_FRAMEWORK.METADATA.DQ_EXPECTATION_MASTER;
INSERT INTO DQ_FRAMEWORK.METADATA.DQ_EXPECTATION_MASTER (EXPECTATION_ID, VALIDATION_NAME, DESCRIPTION, DIMENSION, IS_ACTIVE, CHECK_TYPE, SUB_DIMENSION, INSTRUCTION_TEXT, DQ_ENGINE, EXPECTED_DATATYPE, CHECK_LEVEL) VALUES
    (1, 'expect_column_values_to_be_null', 'Expect the column values to be null.', 'COMPLETENESS', 'Y', 'NULL_CHECK', 'Completeness', 'Please provide the column name and      optionally a value for "mostly" (a float between 0 and 1) to specify the fraction of values expected to be null.', 'SQL', 'ALL', 'ROW'),
    (2, 'expect_column_values_to_not_be_null', 'Expect the column values to not be null', 'COMPLETENESS', 'Y', 'NOT_NULL_CHECK', 'Completeness', 'Provide column name to check non-nulls. Example: cancellation_reason', 'SQL', 'ALL', 'ROW'),
    (3, 'expect_table_row_count_to_be_between', 'Expect the number of rows to be between two values', 'VOLUME', 'Y', 'ROW_COUNT_RANGE', 'Row Count Range', 'Provide min and max row count. Example: 1000, 100000', 'SQL', NULL, 'TABLE'),
    (4, 'expect_table_row_count_to_equal_other_table', 'Expect the number of rows to equal the number in another table within the same database', 'VOLUME', 'Y', 'ROW_COUNT_MATCH', 'Row Count Match', 'Provide table name whose row count should match. Example: customer_dim', 'SQL', NULL, 'TABLE'),
    (5, 'expect_column_values_to_be_recent', 'Expect date column to have values within the last 24 hours for freshness validation.', 'FRESHNESS', 'Y', 'FRESHNESS_CHECK', 'Freshness Check', 'Provide the column name, freshness threshold amount (integer), threshold unit (e.g., ''hours'', ''minutes''), and optionally the timezone.      Example: last_update_date, 24, hours, UTC', 'SQL', 'TIMESTAMP_LTZ, TIMESTAMP_NTZ', 'TABLE'),
    (6, 'expect_column_to_exist', 'Checks for the existence of a specified column within a table.', 'SCHEMA', 'Y', 'COLUMN_EXISTS', 'Column Structure', 'Provide the column name that must exist. Example: user_id', 'SQL', NULL, 'SCHEMA'),
    (7, 'expect_column_values_to_be_of_type', 'Expect a column to contain values of a specified data type', 'SCHEMA', 'Y', 'DATA_TYPE_CHECK', 'Data Type Check', 'Please provide the column which needs to be checked and datatype also in type_. Example: user_id,int', 'SQL', 'ALL', 'SCHEMA'),
    (8, 'expect_table_column_count_to_be_between', 'Expect the number of columns in a table to be between two values', 'SCHEMA', 'Y', 'COLUMN_COUNT_RANGE', 'Column Structure', 'Provide minimum and maximum expected number of columns. Example: 5, 10', 'SQL', NULL, 'SCHEMA'),
    (9, 'expect_table_columns_to_match_set', 'Expect the columns in a table to match an unordered set', 'SCHEMA', 'Y', 'COLUMN_SET_MATCH', 'Column Structure', 'Provide list of expected columns. Example: ["id", "name", "age"]', 'SQL', NULL, 'SCHEMA'),
    (10, 'expect_column_values_to_be_between', 'Expect the column entries to be between a minimum value and a maximum value (inclusive)', 'NUMERIC', 'Y', 'RANGE_CHECK', 'Range Check', 'Provide maximum and minimum value which needs to be checked for a given column. Example: 100,0', 'SQL', 'NUMBER, FLOAT', 'ROW'),
    (11, 'expect_column_max_to_be_between', 'Expect the column maximum to be between a minimum value and a maximum value', 'NUMERIC', 'Y', 'MAX_RANGE_CHECK', 'Range Check', 'Provide minimum and maximum value which needs to be checked for a given column. Example: 0,100', 'SQL', 'NUMBER, FLOAT', 'AGGREGATE'),
    (12, 'expect_column_mean_to_be_between', 'Expect the column mean to be between a minimum value and a maximum value (inclusive)', 'NUMERIC', 'Y', 'MEAN_RANGE_CHECK', 'Statistical Check', 'Provide minimum and maximum values to validate against column mean. Example: 10.5, 50.0', 'SQL', 'NUMBER, FLOAT', 'AGGREGATE'),
    (13, 'expect_column_median_to_be_between', 'Expect the column median to be between a minimum value and a maximum value.', 'NUMERIC', 'Y', 'MEDIAN_RANGE_CHECK', 'Statistical Check', 'Provide minimum and maximum values to validate against column median. Example: 10, 100', 'SQL', 'NUMBER, FLOAT', 'AGGREGATE'),
    (14, 'expect_column_min_to_be_between', 'Expect the column minimum to be between a minimum value and a maximum value.', 'NUMERIC', 'Y', 'MIN_RANGE_CHECK', 'Range Check', 'Provide minimum and maximum value which needs to be checked for a given column. Example: 0,100', 'SQL', 'NUMBER, FLOAT', 'AGGREGATE'),
    (15, 'expect_column_pair_values_a_to_be_greater_than_b', 'Expect the values in column A to be greater than column B', 'NUMERIC', 'Y', 'COL_PAIR_COMPARE', 'Column Pair Range', 'Provide column A and column B to check A > B. Example: selling_price,cost_price', 'SQL', 'NUMBER, FLOAT', 'ROW'),
    (16, 'expect_column_stdev_to_be_between', 'Expect the column standard deviation to be between a minimum value and a maximum value.', 'NUMERIC', 'Y', 'STDEV_RANGE_CHECK', 'Statistical Check', 'Provide minimum and maximum values for column standard deviation. Example: 5.0, 25.0', 'SQL', 'NUMBER, FLOAT', 'AGGREGATE'),
    (17, 'expect_column_sum_to_be_between', 'Expect the column sum to be between a minimum value and a maximum value.', 'NUMERIC', 'Y', 'SUM_RANGE_CHECK', 'Range Check', 'Provide minimum and maximum values for column sum. Example: 100, 5000', 'SQL', 'NUMBER, FLOAT', 'AGGREGATE'),
    (18, 'expect_column_value_lengths_to_be_between', 'Expect the column entries to be strings with length between a minimum value and a maximum value (inclusive).', 'VALIDITY', 'Y', 'LENGTH_CHECK', 'Length Check', 'Provide min and max string lengths. Example: 5,10', 'SQL', 'TEXT, VARCHAR, NUMBER, FLOAT', 'ROW'),
    (19, 'expect_column_values_to_match_regex', 'Expect the column entries to be strings that match a given regular expression', 'VALIDITY', 'Y', 'PATTERN_MATCH', 'Pattern Match', 'Please provide the valid regular expression which needs to be checked.      Example: Valid regex: ^d{2}-d{3}-d{3}-d{4}$ Matching Input: 91-123-456-7890', 'SQL', 'TEXT, VARCHAR', 'ROW'),
    (20, 'expect_column_values_to_not_match_regex', 'Expect the column entries to be strings that do NOT match a given regular expression', 'VALIDITY', 'Y', 'PATTERN_EXCLUSION', 'Pattern Match', 'Provide regex that column entries should NOT match. Example: ^ERR.*', 'SQL', 'TEXT, VARCHAR', 'ROW'),
    (21, 'expect_column_values_to_be_in_set', 'Expect each column value to be in a given set', 'CONFORMITY', 'Y', 'SET_INCLUSION', 'Domain Inclusion', 'Please provide the column name and the set of values expected in that column.      Optionally, include a value for "mostly" (a float between 0 and 1) if you want to allow a fraction of values not to be in the set.', 'SQL', 'TEXT, VARCHAR, NUMBER, FLOAT', 'ROW'),
    (22, 'expect_column_values_to_not_be_in_set', 'Expect column entries to not be in the set', 'VALIDITY', 'Y', 'SET_EXCLUSION', 'Domain Exclusion', 'Please provide the set of values which should not appear in the given column. Example: error,unknown', 'SQL', 'TEXT, VARCHAR, NUMBER, FLOAT', 'ROW'),
    (23, 'expect_column_unique_value_count_to_be_between', 'Expect the number of unique values to be between a minimum value and a maximum value.', 'UNIQUENESS', 'Y', 'UNIQUE_COUNT_RANGE', 'Uniqueness Distribution', 'Provide min and max count for unique values. Example: 10, 100', 'SQL', 'ALL', 'AGGREGATE'),
    (24, 'expect_column_values_to_be_unique', 'Expect each column value to be unique', 'UNIQUENESS', 'Y', 'UNIQUENESS_CHECK', 'Uniqueness Check', 'Please provide column name and optionally a value for "mostly" (float between 0 and 1) to specify the fraction of values expected to be unique.', 'SQL', 'ALL', 'ROW'),
    (25, 'unexpected_rows_expectation', 'Expectation will fail validation if the query returns one or more rows. The WHERE clause defines the fail criteria', 'SQL', 'Y', 'CUSTOM_RULE', 'Business Rule', 'Provide the full SQL query to identify failing rows.', 'SQL', NULL, 'ROW'),
    (26, 'expect_table_row_count_to_equal_source_file', 'Expect the CORE table row count to equal the source-file record count recorded in the audit-control table', 'VOLUME', 'Y', 'SOURCE_FILE_COUNT_MATCH', 'Source File Count Match', 'Optionally provide audit_control_table, sync_level, and target_table in KWARGS. Defaults to PRISM_META_PROD.META.AUDIT_CONTROL / SOURCE_TO_CORE.', 'SQL', NULL, 'TABLE');

-- DQ_EXPECTATION_HANDLER_MAPPING (45 rows)
DELETE FROM DQ_FRAMEWORK.METADATA.DQ_EXPECTATION_HANDLER_MAPPING;
INSERT INTO DQ_FRAMEWORK.METADATA.DQ_EXPECTATION_HANDLER_MAPPING (CHECK_TYPE, EXPECTATION_TYPE, SP_NAME, HANDLER_VERSION, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES
    ('COLUMN_COUNT_EQUAL_CHECK', 'expect_table_column_count_to_equal', 'SP_TABLE_COLUMN_COUNT_EQUAL_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('COLUMN_COUNT_RANGE_CHECK', 'expect_table_column_count_to_be_between', 'SP_TABLE_COLUMN_COUNT_BETWEEN_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('COLUMN_DISTINCT_VALUES_TO_CONTAIN_SET', 'expect_column_distinct_values_to_contain_set', 'SP_COLUMN_DISTINCT_VALUES_TO_CONTAIN_SET', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('COLUMN_EXISTS_CHECK', 'expect_column_to_exist', 'SP_COLUMN_TO_EXIST_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('COLUMN_PAIR_EQUAL_CHECK', 'expect_column_pair_values_to_be_equal', 'SP_COLUMN_PAIR_EQUAL_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('COLUMN_PAIR_IN_SET_CHECK', 'expect_column_pair_values_to_be_in_set', 'SP_COLUMN_PAIR_IN_SET_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('COLUMN_VALUE_Z_SCORES_TO_BE_LESS_THAN', 'expect_column_value_z_scores_to_be_less_than', 'SP_ZSCORE_LESS_THAN_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('COMMON_VALUE_IN_SET', 'expect_column_most_common_value_to_be_in_set', 'SP_MOST_COMMON_VALUE_IN_SET_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('COMPOUND_COLUMNS_TO_BE_UNIQUE', 'expect_compound_columns_to_be_unique', 'SP_COMPOUND_COLUMNS_UNIQUE_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('CUSTOM_SQL_CHECK', 'unexpected_rows_expectation', 'SP_UNEXPECTED_ROWS_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('DATA_TYPE_CHECK', 'expect_column_values_to_be_of_type', 'SP_DATA_TYPE_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('DATE_FORMAT_CHECK', 'expect_column_values_to_be_in_given_format', 'SP_DATE_FORMAT_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('DISTINCT_IN_SET_CHECK', 'expect_column_distinct_values_to_be_in_set', 'SP_DISTINCT_VALUES_IN_SET_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('DISTINCT_VALUES_EQUAL_SET_CHECK', 'expect_column_distinct_values_to_equal_set', 'SP_DISTINCT_VALUES_EQUAL_SET_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('FRESHNESS_CHECK', 'expect_column_values_to_be_recent', 'SP_FRESHNESS_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('MAX_RANGE_CHECK', 'expect_column_max_to_be_between', 'SP_MAX_VALUE_BETWEEN_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('MEAN_RANGE_CHECK', 'expect_column_mean_to_be_between', 'SP_MEAN_RANGE_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('MEDIAN_RANGE_CHECK', 'expect_column_median_to_be_between', 'SP_MEDIAN_RANGE_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('MIN_RANGE_CHECK', 'expect_column_min_to_be_between', 'SP_MIN_VALUE_BETWEEN_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('MULTI_COL_SUM_CHECK', 'expect_multicolumn_sum_to_equal', 'SP_MULTICOLUMN_SUM_EQUAL_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('NOT_NULL_CHECK', 'expect_column_values_to_not_be_null', 'SP_NOT_NULL_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('NULL_ONLY_CHECK', 'expect_column_values_to_be_null', 'SP_NULL_ONLY_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('PAIR_VALUES_A_GREATER_THAN_B', 'expect_column_pair_values_a_to_be_greater_than_b', 'SP_COLUMN_PAIR_A_GREATER_THAN_B', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('PROPORTIONAL_NULL_CHECK', 'expect_column_proportion_of_non_null_value_to_be_between', 'SP_PROPORTION_NON_NULL_BETWEEN_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('PROPORTION_UNIQUE_VALUE_BETWEEN_CHECK', 'expect_column_proportion_of_unique_values_to_be_between', 'SP_PROPORTION_UNIQUE_VALUE_BETWEEN_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('RANGE_VALUE_CHECK', 'expect_column_values_to_be_between', 'SP_RANGE_VALUE_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('REGEX_MATCH_CHECK', 'expect_column_values_to_match_regex', 'SP_REGEX_MATCH_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('REGEX_MATCH_LIST_CHECK', 'expect_column_values_to_match_like_pattern_list', 'SP_REGEX_MATCH_LIST_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('REGEX_NOT_MATCH_CHECK', 'expect_column_values_to_not_match_regex', 'SP_REGEX_NOT_MATCH_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('REGEX_NOT_MATCH_LIST_CHECK', 'expect_column_values_to_not_match_regex_list', 'SP_REGEX_NOT_MATCH_LIST_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('SOURCE_FILE_COUNT_MATCH', 'expect_table_row_count_to_equal_source_file', 'SP_TABLE_ROW_COUNT_EQUAL_SOURCE_FILE_CHECK', 'v1.0', TRUE, '2026-06-21 01:48:56.521000', '2026-06-21 01:48:56.521000'),
    ('STDEV_RANGE_CHECK', 'expect_column_stdev_to_be_between', 'SP_STDEV_VALUE_BETWEEN_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('SUM_RANGE_CHECK', 'expect_column_sum_to_be_between', 'SP_SUM_RANGE_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('TABLE_COLUMNS_MATCH_ORDERED_LIST_CHECK', 'expect_table_columns_to_match_ordered_list', 'SP_TABLE_COLUMNS_MATCH_ORDERED_LIST_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('TABLE_COLUMNS_MATCH_SET_CHECK', 'expect_table_columns_to_match_set', 'SP_TABLE_COLUMNS_MATCH_SET_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('TABLE_ROW_COUNT_CHECK', 'expect_table_row_count_to_be_between', 'SP_TABLE_ROW_COUNT_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('TABLE_ROW_COUNT_CMP_CHECK', 'expect_table_row_count_to_equal_other_table', 'SP_TABLE_ROW_COUNT_EQUAL_OTHER_TABLE_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('TABLE_ROW_COUNT_EQUAL_CHECK', 'expect_table_row_count_to_equal', 'SP_TABLE_ROW_COUNT_EQUAL_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('UNIQUENESS_CHECK', 'expect_column_values_to_be_unique', 'SP_UNIQUENESS_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('UNIQUE_VALUES_WITHIN_RECORD_CHECK', 'expect_select_column_values_to_be_unique_within_record', 'SP_UNIQUE_VALUES_WITHIN_RECORD_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('UNIQUE_VALUE_COUNT_BETWEEN_CHECK', 'expect_column_unique_value_count_to_be_between', 'SP_UNIQUE_VALUE_COUNT_BETWEEN_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('VALUE_IN_SET_CHECK', 'expect_column_values_to_be_in_set', 'SP_VALUE_IN_SET_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('VALUE_LENGTH_EQUAL_CHECK', 'expect_column_value_lengths_to_equal', 'SP_VALUE_LENGTH_EQUAL_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('VALUE_LENGTH_RANGE_CHECK', 'expect_column_value_lengths_to_be_between', 'SP_VALUE_LENGTH_BETWEEN_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000'),
    ('VALUE_NOT_IN_CHECK', 'expect_column_values_to_not_be_in_set', 'SP_VALUE_NOT_IN_SET_CHECK', 'v1.0', TRUE, '2026-06-15 04:17:20.862000', '2026-06-15 04:17:20.862000');

-- DQ_EXPECTATION_ARGUMENTS (100 rows)
DELETE FROM DQ_FRAMEWORK.METADATA.DQ_EXPECTATION_ARGUMENTS;
INSERT INTO DQ_FRAMEWORK.METADATA.DQ_EXPECTATION_ARGUMENTS (EXPECTATION_ARG_ID, EXPECTATION_ID, EXPECTATION_NAME, ARGUMENT_NAME, ARGUMENT_TYPE, ARGUMENT_DESC, IS_MANDATORY, DEFAULT_VALUE, HELP_TEXT) VALUES
    (101, 1, 'expect_column_values_to_be_null', 'column', 'str', 'The column name', TRUE, NULL, 'email'),
    (102, 1, 'expect_column_values_to_be_null', 'mostly', 'number or None', 'Successful if at least `mostly` fraction of values match the Expectation. Default 1.', FALSE, NULL, '1.0'),
    (103, 2, 'expect_column_values_to_not_be_null', 'column', 'str', 'The column name', TRUE, NULL, 'customer_id'),
    (104, 2, 'expect_column_values_to_not_be_null', 'mostly', 'number or None', 'Successful if at least `mostly` fraction of values match the Expectation. Default 1.', FALSE, NULL, '0.95'),
    (105, 3, 'expect_table_row_count_to_be_between', 'strict_min', 'boolean', 'If True, the row count must be strictly larger than min_value', FALSE, 'FALSE', 'false'),
    (106, 3, 'expect_table_row_count_to_be_between', 'strict_max', 'boolean', 'If True, the row count must be strictly smaller than max_value', FALSE, 'FALSE', 'false'),
    (107, 3, 'expect_table_row_count_to_be_between', 'min_value', 'int or None', 'The minimum number of rows, inclusive', TRUE, NULL, '1'),
    (108, 3, 'expect_table_row_count_to_be_between', 'max_value', 'int or None', 'The maximum number of rows, inclusive', TRUE, NULL, '1000000'),
    (109, 4, 'expect_table_row_count_to_equal_other_table', 'other_dataset_name', 'str', 'LEGACY: source as a registered dataset name. Prefer source_database/source_schema/source_table.', FALSE, NULL, 'curated.sales_orders'),
    (110, 5, 'expect_column_values_to_be_recent', 'freshness_threshold_value', 'int', 'The maximum time elapsed since the data was generated or updated that is still considered "fresh." This is the numerical part of the threshold.', TRUE, NULL, '2'),
    (111, 5, 'expect_column_values_to_be_recent', 'freshness_threshold_unit', 'str', 'The unit of time for the threshold amount (e.g., ''hours'', ''seconds'', ''minutes''). This defines what the amount is measuring.', TRUE, NULL, 'day'),
    (112, 5, 'expect_column_values_to_be_recent', 'timezone', 'str', 'The time zone used for the current time when calculating the age of the data.      This is crucial for accurate comparisons, especially when data is ingested from different geographical locations.', FALSE, NULL, 'UTC'),
    (113, 5, 'expect_column_values_to_be_recent', 'column', 'str', 'The column name', TRUE, NULL, 'updated_at'),
    (114, 6, 'expect_column_to_exist', 'column', 'str', 'The column name', TRUE, NULL, 'customer_id'),
    (115, 7, 'expect_column_values_to_be_of_type', 'column', 'str', 'The column name', TRUE, NULL, 'age'),
    (116, 7, 'expect_column_values_to_be_of_type', 'type_', 'str', 'A string representing the data type that each column should have as entries.      Valid types are defined by the current backend implementation and are dynamically loaded', TRUE, NULL, 'int'),
    (117, 8, 'expect_table_column_count_to_be_between', 'min_value', 'int or None', 'The minimum number of columns, inclusive', TRUE, NULL, '5'),
    (118, 8, 'expect_table_column_count_to_be_between', 'max_value', 'int or None', 'The maximum number of columns, inclusive', TRUE, NULL, '100'),
    (119, 9, 'expect_table_columns_to_match_set', 'column_set', 'list of str', 'The column names, in any order', TRUE, NULL, '[''id'',''name'',''CS:Amount'']'),
    (120, 9, 'expect_table_columns_to_match_set', 'exact_match', 'boolean', 'If True, the list of columns must exactly match the observed columns.      If False, observed columns must include column_set but additional columns will pass', FALSE, 'TRUE', 'true'),
    (121, 10, 'expect_column_values_to_be_between', 'strict_min', 'boolean', 'If True, values must be strictly larger than min_value. Default=False', FALSE, 'FALSE', 'false'),
    (122, 10, 'expect_column_values_to_be_between', 'strict_max', 'boolean', 'If True, values must be strictly smaller than max_value. Default=False', FALSE, 'FALSE', 'true'),
    (123, 10, 'expect_column_values_to_be_between', 'column', 'str', 'The column name', TRUE, NULL, 'amount'),
    (124, 10, 'expect_column_values_to_be_between', 'min_value', 'comparable type or None', 'The minimum value for a column entry', TRUE, NULL, '0'),
    (125, 10, 'expect_column_values_to_be_between', 'max_value', 'comparable type or None', 'The maximum value for a column entry', TRUE, NULL, '10000'),
    (126, 10, 'expect_column_values_to_be_between', 'mostly', 'number or None', 'Successful if at least `mostly` fraction of values match the Expectation. Default 1.', FALSE, NULL, '0.99'),
    (127, 11, 'expect_column_max_to_be_between', 'strict_min', 'boolean', 'If True, the minimal column minimum must be strictly larger than min_value, default=False', FALSE, 'FALSE', 'false'),
    (128, 11, 'expect_column_max_to_be_between', 'strict_max', 'boolean', 'If True, the maximal column minimum must be strictly smaller than max_value, default=False', FALSE, 'FALSE', 'false'),
    (129, 11, 'expect_column_max_to_be_between', 'column', 'str', 'The column name', TRUE, NULL, 'amount'),
    (130, 11, 'expect_column_max_to_be_between', 'min_value', 'comparable type or None', 'The minimal column minimum allowed', TRUE, NULL, '0'),
    (131, 11, 'expect_column_max_to_be_between', 'max_value', 'comparable type or None', 'The maximal column minimum allowed.', TRUE, NULL, '1000000'),
    (132, 12, 'expect_column_mean_to_be_between', 'strict_min', 'boolean', 'If True, the column mean must be strictly larger than min_value, default=False', FALSE, 'FALSE', 'false'),
    (133, 12, 'expect_column_mean_to_be_between', 'strict_max', 'boolean', 'If True, the column mean must be strictly smaller than max_value, default=False', FALSE, 'FALSE', 'false'),
    (134, 12, 'expect_column_mean_to_be_between', 'column', 'str', 'The column name', TRUE, NULL, 'price'),
    (135, 12, 'expect_column_mean_to_be_between', 'min_value', 'float or None', 'The minimum value for the column mean.', TRUE, NULL, '0.0'),
    (136, 12, 'expect_column_mean_to_be_between', 'max_value', 'float or None', 'The maximum value for the column mean', TRUE, NULL, '500.0'),
    (137, 13, 'expect_column_median_to_be_between', 'strict_min', 'boolean', 'If True, the column median must be strictly larger than min_value, default=False', FALSE, 'FALSE', 'false'),
    (138, 13, 'expect_column_median_to_be_between', 'strict_max', 'boolean', 'If True, the column median must be strictly smaller than max_value, default=False', FALSE, 'FALSE', 'false'),
    (139, 13, 'expect_column_median_to_be_between', 'column', 'str', 'The column name', TRUE, NULL, 'delivery_days'),
    (140, 13, 'expect_column_median_to_be_between', 'min_value', 'int or None', 'The minimum value for the column median', TRUE, NULL, '0'),
    (141, 13, 'expect_column_median_to_be_between', 'max_value', 'int or None', 'The maximum value for the column median', TRUE, NULL, '30'),
    (142, 14, 'expect_column_min_to_be_between', 'strict_min', 'boolean', 'If True, the minimal column minimum must be strictly larger than min_value, default=False', FALSE, 'FALSE', 'false'),
    (143, 14, 'expect_column_min_to_be_between', 'strict_max', 'boolean', 'If True, the maximal column minimum must be strictly smaller than max_value, default=False', FALSE, 'FALSE', 'false'),
    (144, 14, 'expect_column_min_to_be_between', 'column', 'str', 'The column name', TRUE, NULL, 'created_at'),
    (145, 14, 'expect_column_min_to_be_between', 'min_value', 'comparable type or None', 'The minimal column minimum allowed', TRUE, NULL, '2020-01-01'),
    (146, 14, 'expect_column_min_to_be_between', 'max_value', 'comparable type or None', 'The maximal column minimum allowed.', TRUE, NULL, '2026-01-01'),
    (147, 15, 'expect_column_pair_values_a_to_be_greater_than_b', 'ignore_row_if', 'str', '"both_values_are_missing", "either_value_is_missing", "neither".      If specified, sets the condition on which a given row is to be ignored. Default "neither".', FALSE, NULL, 'both_values_are_missing'),
    (148, 15, 'expect_column_pair_values_a_to_be_greater_than_b', 'mostly', 'number or None', 'Successful if at least `mostly` fraction of values match the Expectation. Default 1.', FALSE, NULL, '0.97'),
    (149, 15, 'expect_column_pair_values_a_to_be_greater_than_b', 'or_equal', 'boolean or None', 'If True, then values can be equal, not strictly greater', FALSE, NULL, 'true'),
    (150, 15, 'expect_column_pair_values_a_to_be_greater_than_b', 'column_A', 'str', 'The first column name', TRUE, NULL, 'delivered_qty'),
    (151, 15, 'expect_column_pair_values_a_to_be_greater_than_b', 'column_B', 'str', 'The second column name', TRUE, NULL, 'ordered_qty'),
    (152, 16, 'expect_column_stdev_to_be_between', 'strict_min', 'boolean', 'If True, the column standard deviation must be strictly larger than min_value', FALSE, 'FALSE', 'false'),
    (153, 16, 'expect_column_stdev_to_be_between', 'strict_max', 'boolean', 'If True, the column standard deviation must be strictly smaller than max_value', FALSE, 'FALSE', 'false'),
    (154, 16, 'expect_column_stdev_to_be_between', 'column', 'str', 'The column name', TRUE, NULL, 'amount'),
    (155, 16, 'expect_column_stdev_to_be_between', 'min_value', 'float or None', 'The minimum value for the column standard deviation', TRUE, NULL, '0.0'),
    (156, 16, 'expect_column_stdev_to_be_between', 'max_value', 'float or None', 'The maximum value for the column standard deviation', TRUE, NULL, '1000.0'),
    (157, 17, 'expect_column_sum_to_be_between', 'strict_min', 'boolean', 'If True, the minimal sum must be strictly larger than min_value', FALSE, 'FALSE', 'false'),
    (158, 17, 'expect_column_sum_to_be_between', 'strict_max', 'boolean', 'If True, the maximal sum must be strictly smaller than max_value', FALSE, 'FALSE', 'false'),
    (159, 17, 'expect_column_sum_to_be_between', 'column', 'str', 'The column name', TRUE, NULL, 'net_sales'),
    (160, 17, 'expect_column_sum_to_be_between', 'min_value', 'comparable type or None', 'The minimal sum allowed', TRUE, NULL, '0'),
    (161, 17, 'expect_column_sum_to_be_between', 'max_value', 'comparable type or None', 'The maximal sum allowed', TRUE, NULL, '100000000'),
    (162, 18, 'expect_column_value_lengths_to_be_between', 'strict_min', 'bool', 'If True, values must be strictly larger than min_value', FALSE, 'FALSE', 'false'),
    (163, 18, 'expect_column_value_lengths_to_be_between', 'strict_max', 'bool', 'If True, values must be strictly smaller than max_value', FALSE, 'FALSE', 'false'),
    (164, 18, 'expect_column_value_lengths_to_be_between', 'column', 'str', 'The column name', TRUE, NULL, 'phone'),
    (165, 18, 'expect_column_value_lengths_to_be_between', 'min_value', 'int or None', 'The minimum value for a column entry length', TRUE, NULL, '10'),
    (166, 18, 'expect_column_value_lengths_to_be_between', 'mostly', 'number or None', 'Successful if at least `mostly` fraction of values match the Expectation. Default 1.', FALSE, NULL, '0.98'),
    (167, 18, 'expect_column_value_lengths_to_be_between', 'max_value', 'int or None', 'The maximum value for a column entry length', TRUE, NULL, '15'),
    (168, 19, 'expect_column_values_to_match_regex', 'column', 'str', 'The column name', TRUE, NULL, 'email'),
    (169, 19, 'expect_column_values_to_match_regex', 'mostly', 'number or None', 'Successful if at least `mostly` fraction of values match the Expectation. Default 1.', FALSE, NULL, '0.99'),
    (170, 19, 'expect_column_values_to_match_regex', 'regex', 'str', 'The regular expression the column entries should match', TRUE, NULL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,}$'),
    (171, 20, 'expect_column_values_to_not_match_regex', 'column', 'str', 'The column name', TRUE, NULL, 'comments'),
    (172, 20, 'expect_column_values_to_not_match_regex', 'mostly', 'number or None', 'Successful if at least `mostly` fraction of values match the Expectation. Default 1.', FALSE, NULL, '0.95'),
    (173, 20, 'expect_column_values_to_not_match_regex', 'regex', 'str', 'The regular expression the column entries should NOT match.', TRUE, NULL, '(?i)^test'),
    (174, 21, 'expect_column_values_to_be_in_set', 'column', 'str', 'The column name', TRUE, NULL, 'status'),
    (175, 21, 'expect_column_values_to_be_in_set', 'mostly', 'number or None', 'Successful if at least `mostly` fraction of values match the Expectation. Default 1.', FALSE, NULL, '1.0'),
    (176, 21, 'expect_column_values_to_be_in_set', 'value_set', 'set-like', 'A set of objects used for comparison.', TRUE, NULL, '[''ACTIVE'',''INACTIVE'']'),
    (177, 22, 'expect_column_values_to_not_be_in_set', 'column', 'str', 'The column name', TRUE, NULL, 'status'),
    (178, 22, 'expect_column_values_to_not_be_in_set', 'mostly', 'number or None', 'Successful if at least `mostly` fraction of values match the Expectation. Default 1.', FALSE, NULL, '0.99'),
    (179, 22, 'expect_column_values_to_not_be_in_set', 'value_set', 'set-like', 'A set of objects used for comparison.', TRUE, NULL, '[''UNKNOWN'',''N/A'']'),
    (180, 23, 'expect_column_unique_value_count_to_be_between', 'strict_min', 'bool', 'If True, the column must have strictly more unique value count than min_value to pass', FALSE, 'FALSE', 'false'),
    (181, 23, 'expect_column_unique_value_count_to_be_between', 'strict_max', 'bool', 'If True, the column must have strictly fewer unique value count than max_value to pass', FALSE, 'FALSE', 'false'),
    (182, 23, 'expect_column_unique_value_count_to_be_between', 'column', 'str', 'The column name', TRUE, NULL, 'store_id'),
    (183, 23, 'expect_column_unique_value_count_to_be_between', 'min_value', 'int or None', 'The minimum number of unique values allowed', TRUE, NULL, '1'),
    (184, 23, 'expect_column_unique_value_count_to_be_between', 'max_value', 'int or None', 'The maximum number of unique values allowed', TRUE, NULL, '1000'),
    (185, 24, 'expect_column_values_to_be_unique', 'mostly', 'number or None', 'Successful if at least `mostly` fraction of values match the Expectation. Default 1.', FALSE, NULL, '1.0'),
    (186, 24, 'expect_column_values_to_be_unique', 'column', 'str', 'The column name', TRUE, NULL, 'order_id'),
    (187, 25, 'unexpected_rows_expectation', 'unexpected_rows_query', 'str', 'A SQL to be executed for validation.Provide fully qualified table (dbname.schemaname.table)', TRUE, NULL, 'SELECT * FROM DATASET_NAME WHERE COLUMN_NAME (Filter Condition/Logic)'),
    (210, 4, 'expect_table_row_count_to_equal_other_table', 'scd_type', 'int', 'Recon mode: 0/blank = plain row-count equality, 1 = SCD1 total dedup recon, 2 = SCD2 active/inactive recon', FALSE, '0', '0, 1 or 2'),
    (211, 4, 'expect_table_row_count_to_equal_other_table', 'partition_keys', 'list', 'Business keys used to dedup the SOURCE rows and match into the target (required for SCD1/SCD2)', FALSE, NULL, 'Comma-separated keys'),
    (212, 4, 'expect_table_row_count_to_equal_other_table', 'active_flag_col', 'str', 'Active/inactive flag column on this rule''s TARGET (conformed) dataset (SCD2)', FALSE, 'IS_ACTIVE', 'e.g. IS_ACTIVE'),
    (213, 4, 'expect_table_row_count_to_equal_other_table', 'active_value', 'str', 'Value denoting active record on the target (SCD2)', FALSE, 'Y', 'e.g. Y'),
    (214, 4, 'expect_table_row_count_to_equal_other_table', 'inactive_value', 'str', 'Value denoting inactive record on the target (SCD2)', FALSE, 'N', 'e.g. N'),
    (215, 4, 'expect_table_row_count_to_equal_other_table', 'core_insert_date_col', 'str', 'SOURCE insert/load timestamp column for dedup + latest-batch filter (SCD1/2)', FALSE, 'INSERT_DATE_TIME', 'e.g. INSERT_DATE_TIME'),
    (216, 4, 'expect_table_row_count_to_equal_other_table', 'conformed_update_date_col', 'str', 'TARGET (this rule''s dataset) update timestamp column for latest-batch filter (SCD1/2)', FALSE, 'UPDATE_DATE_TIME', 'e.g. UPDATE_DATE_TIME'),
    (217, 4, 'expect_table_row_count_to_equal_other_table', 'source_database', 'str', 'SOURCE (core) database � the table reconciled against (this rule''s dataset is the target)', TRUE, NULL, 'e.g. PRISM_MDM_PROD'),
    (218, 4, 'expect_table_row_count_to_equal_other_table', 'source_schema', 'str', 'SOURCE (core) schema', TRUE, NULL, 'e.g. CORE'),
    (219, 4, 'expect_table_row_count_to_equal_other_table', 'source_table', 'str', 'SOURCE (core) table (exclude the rule''s own table)', TRUE, NULL, 'e.g. MDM_PRODUCT'),
    (220, 26, 'expect_table_row_count_to_equal_source_file', 'audit_control_table', 'str', 'Fully qualified audit control table', FALSE, 'PRISM_META_PROD.META.AUDIT_CONTROL', 'PRISM_META_PROD.META.AUDIT_CONTROL'),
    (221, 26, 'expect_table_row_count_to_equal_source_file', 'sync_level', 'str', 'Sync level filter value', FALSE, 'SOURCE_TO_CORE', 'SOURCE_TO_CORE'),
    (222, 26, 'expect_table_row_count_to_equal_source_file', 'target_table', 'str', 'Target table override (defaults to dataset table)', FALSE, 'None', 'MY_DB.MY_SCHEMA.MY_TABLE');
