-- Add clustering keys to high-volume tables for query performance

USE DATABASE DQ_FRAMEWORK;
USE SCHEMA METADATA;

-- DQ_RULE_RESULTS: most queries filter by DATASET_ID and DATASET_RUN_ID
ALTER TABLE IF EXISTS DQ_RULE_RESULTS
    CLUSTER BY (DATASET_ID, DATASET_RUN_ID);

-- DQ_RULE_AUDIT_LOG: most queries filter by DATASET_RUN_ID and RULE_CONFIG_ID
ALTER TABLE IF EXISTS DQ_RULE_AUDIT_LOG
    CLUSTER BY (DATASET_RUN_ID, RULE_CONFIG_ID);

-- DQ_FAILED_ROW_KEYS: queried by run + rule for failure drill-down
ALTER TABLE IF EXISTS DQ_FAILED_ROW_KEYS
    CLUSTER BY (DATASET_RUN_ID, RULE_CONFIG_ID);

-- DQ_DATASET_RUN_LOG: commonly filtered by DATASET_ID and timestamp
ALTER TABLE IF EXISTS DQ_DATASET_RUN_LOG
    CLUSTER BY (DATASET_ID, CREATED_TIMESTAMP);
